{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Phase 2: Adversarial Detection EDA\n",
    "### Identifying Agentic 'Burst' Signatures"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# 1. Load the data generated by your GitHub Action\n",
    "# Note: We use '../' to go up one folder from 'notebooks' to find 'data'\n",
    "df = pd.read_csv('../data/raw/transactions.csv')\n",
    "\n",
    "# 2. Identify 'Burst' Signatures\n",
    "velocity_df = df.groupby('timestamp').size().reset_index(name='transaction_count')\n",
    "\n",
    "burst_attacks = velocity_df[velocity_df['transaction_count'] > 10]\n",
    "print(f'Detected {len(burst_attacks)} potential Agentic Burst Attacks.')\n",
    "\n",
    "# 3. Unmasking the Hydra\n",
    "print('\\n--- Sample of Detected Burst Transactions ---')\n",
    "print(df[df['timestamp'].isin(burst_attacks['timestamp'])].head())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
